name: Publish Python distribution to PyPI and TestPyPI
on:
  push:
    tags:
      - '*'
jobs:
  build-and-publish:
    name: Publish Python distribution to PyPI and TestPyPI
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@master
    
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: >-
        python -m pip --no-cache-dir --upgrade --quiet install pip flit

    - name: Build a binary wheel and a source tarball
      run: >-
        python -m flit build

    - name: Publish distribution to TestPyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: ${{ secrets.PYPI_ACCESS_USERNAME }}
        password: ${{ secrets.PYPI_ACCESS_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: ${{ secrets.PYPI_ACCESS_USERNAME }}
        password: ${{ secrets.PYPI_ACCESS_TOKEN }}
